version: '3'
services:
  web-app:
    build:
      context: ./web-app
    ports:
      - "4200:80"
    depends_on:
      - backend-server

  backend-server:
    build:
      context: ./backend-server
    ports:
      - "3000:3000"
    environment:
      - GH_TOKEN=